version: "3"

services: 
    app:
        build: .
        depends_on: 
            - elasticsearch
            - kibana
        environment:
            - ES_HOST=elasticsearch
            - ES_PORT=9200
            - ES_PROTO=http
            - ET_HOST=eventide
            - ET_USERNAME=message_store
            - ET_PASSWORD=
            - NODE_ENV=development
            - ET_PORT=5432
        links: 
            - elasticsearch
            - kibana
        container_name: node-elastic
        network_mode: bridge
        ports:
            - 3000:3000
            - 5858:5858
        volumes:
            - ./:/code
            - /code/node_modules

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        container_name: elasticsearch
        network_mode: bridge
        environment:
          - cluster.name=docker-cluster
          - bootstrap.memory_lock=true
          - discovery.type=single-node
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        ports:
          - 9200:9200
        expose:
          - 9200

    kibana:
        image: docker.elastic.co/kibana/kibana:7.7.0
        container_name: kibana
        network_mode: bridge
        environment:
            SERVER_NAME: kibana
            MONITORING_ENABLED: "true"
            ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
        depends_on:
            - elasticsearch
        links:
            - elasticsearch
        ports:
            - 5601:5601
        expose:
            - 5601